### ISSUE TITLE
Remapping up/down

### ISSUE THREAD

**Issue by amiroslaw** [d99kris/nchat#132]
**Description**:
I want to remap selecting message, but I lose ability to selecting contacts in address book and  contact selector.

What I see there are no separates actions for moving through messages and items in address book/contact selector only up and down bindings.

**How to reproduce it**:
Change keybindings
delete_line_after_cursor=\33\153
down=KEY_CTRLJ
up=KEY_CTRLK
Open adreess book or select_contact - c-j/c-k do nothing.

**Environment**:
- Version: 3.73
- OS / distro: Manjaro

**Comment by d99kris** [comment]
Hi @amiroslaw - some ctrl-keys are not ideal to use as keybindings in the terminal due to having same effect as other common keys, for example:
`KEY_CTRLJ` same as`KEY_ENTER`
`KEY_CTRLH` same as `KEY_BACKSPACE`

Anyway, you should be able to use for example:
```
down=KEY_CTRLG
up=KEY_CTRLK
```
And to be on the safe side, ensure you other functions using the same keys, i.e. change:
```
delete_line_after_cursor=KEY_CTRLK
toggle_help=KEY_CTRLG
``` 
to
```
delete_line_after_cursor=
toggle_help=
``` 
This works for me, tested on latest v3.79. I'll proceed to close this issue, but feel free to re-open it if you're still facing problems.
