### ISSUE TITLE
Handle different backspace key codes

### ISSUE THREAD

**Issue by bit9tream** [d99kris/nchat#14]
[That happens when I try to press ESC](https://imgur.com/a/ccez4AA)

I need to press Ctrl+H instead of backspace to delete last character
It will be good if nchat supports different backspace key codes

**Comment by d99kris** [comment]
Hi @bit9tream - nchat does support configurable key bindings, so it should be possible to configure it to use for example Ctrl+H instead of backspace. Can you try edit your `~/.nchat/uidefault.conf` and change the key_backspace line to:
```
key_backspace=KEY_CTRLH
```
I tested it on my Linux system and it seems to work. Please let me know if it solves your problem.

**Comment by bit9tream** [comment]
Thanks
Now all works fine
