### ISSUE TITLE
unable to enable/disable emoji display

### ISSUE THREAD

**Issue by alohawolf** [d99kris/nchat#15]
control-e nor setting emoji=0 effects emoji display

It may be helpful for things like this, to have a status line on the bottom, I just can't think of what else might be useful yet to put in there, what other state changes there could be

**Comment by d99kris** [comment]
Is this affecting the contact list or the messages view? Or perhaps the text input field?
I believe it's working fine for the messages view, but there might be some bug for the others.

**Comment by d99kris** [comment]
Hi @alohawolf - do you have some more information about this issue?

To me it looks like Telegram itself does not permit emojis in contact/group names, so I think there's nothing to enable/disable there. 

As for the chat history, I believe Ctrl+e works fine to enable/disable showing emojis / vs their textual counter-part.

For the message input field, Ctrl+e does not have immediate effect on already entered text, due to some complexity, but it does have the intended effect for typing going forward.

**Comment by alohawolf** [comment]
Telegram does allow emoji in contact/group names, but not in usernames.

I was expecting it to disable them in visible usernames as well as text content in the chats

**Comment by d99kris** [comment]
Ah thanks! I was using web.telegram.com which did not permit emoji in the names, but in the android app I'm able. Okay, will take a look at this!
