### ISSUE TITLE
Unable to acquire lock after closing terminal window

### ISSUE THREAD

**Issue by craftyarch** [d99kris/nchat#281]
Firstly thank you for your great piece of software. Saves me tons of time and is superb to use.
Your time is most appreciated.
At times I experience the following. I hope bug is an acceptable label

**Description**:
When I mistaken close nchat by killing the terminal window, I cannot reload the application unless I sign in again after deleting config files. nchat reports that it cannot 
error: unable to acquire lock for /home/****/.config/nchat
       only one nchat session per account/confdir is supported.

**How to reproduce it**:
Prematurely close the terminal window before exiting.

**Environment**:
Linux Gentoo
dwm

**Comment by d99kris** [comment]
Hi @craftyarch - thanks for the positive feedback 👍 

Regarding the issue, I have not been able to reproduce the same here (yet). Maybe some more information can help:
1. Which terminal emulator are you using? 
2. How is the terminal window closed (pressing window close button with mouse click, exiting window manager, or something else)?

Generally when a terminal is closed, it would signal SIGHUP to its process, which then would terminate - and in the case of nchat, its file/dir locks would be released.

As a temporary workaround, instead of deleting config and performing setup again, you can try to manually just kill the nchat process with the following command:
```
killall nchat
```

**Comment by craftyarch** [comment]
Hi @d99kris

Thanks for the reply. You are right. Closing the window using dwm windows manager on Gentoo linux with alacrity terminal does not reproduce the problem. Apologies, I jumped to an incorrect conclusion. 

However, I have been able to do this somehow on my gentoo and arch linux machine. I will keep trying to find the culprit and come back with better feedback when I know. I will use the killall command as a workaround and close the issue until I have something concrete. 

Thanks again.
