### ISSUE TITLE
Feature request: Shell Integration

### ISSUE THREAD

**Issue by syswraith** [d99kris/nchat#287]
### Discussed in https://github.com/d99kris/nchat/discussions/285

<div type='discussions-op-text'>

<sup>Originally posted by **syswraith** August 24, 2024</sup>
Feature request for adding vi(m)-like shell integration for sending the output of shell commands as messages directly as messages. Similar to how vi implements line and section wands (more info about it at  https://rwx.gg/tools/editors/vi/how/magic/)</div>

**Comment by d99kris** [comment]
Hi - in this project the `Discussions` section is used for reporting feature requests, and the `Issues` section is for reporting bugs. Since there is already a discussion topic #285 for this, I will proceed to close this issue.

Side-note: There is one exception - for feature requests that gets approved and implemented I will create an issue from the discussion just before pushing the commit, and reference that issue in the commit message. This is because Github does not support referencing discussions from commit messages.
