### ISSUE TITLE
Custom Terminal titles with support of chat names

### ISSUE THREAD

**Issue by Bellavene** [d99kris/nchat#62]
Would be great to see active chat name in the terminal title

**Comment by d99kris** [comment]
I'm not sure whether this can be easily supported. Nchat uses ncurses, and I'm concerned updating title (a raw write to terminal) may conflict with the ncurses terminal buffering. I'll leave this issue open for now, in case I (or someone else) find some portable way to support this.

**Comment by d99kris** [comment]
I've done some research and found that it is not possible (well safe) to send raw terminal control codes from within an ncurses application (we can do it at startup/shutdown only, because then ncurses is not yet "running"). And switching from ncurses to some other library/framework is not an option (just too much work), so I'll have to close this issue as out of scope for nchat.
